import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/navbar';


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  cart
}: Readonly<{
  children: React.ReactNode;
  cart:any[];
}>) {
  
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <Navbar cart={cart} />
        {children}
        </body>
    </html>
  );
}
